name: wishden
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  one_context: ^4.0.0
  shared_preferences: ^2.2.3
  stacked: ^3.4.2
  gap: ^3.0.1
  shimmer: ^3.0.0
  go_router: ^14.1.1
  get_it: ^7.7.0
  lottie: ^3.1.2
  firebase_core: ^3.3.0
  web_socket_channel: ^3.0.1
  url_launcher: ^6.3.0
  intl: ^0.18.1
  flutter_native_splash: ^2.4.0
  stacked_services: ^1.3.0
  iconsax_flutter: ^1.0.0
  animated_text_kit: ^4.2.2
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_tawkto: ^0.0.3
  country_pickers: ^3.0.1
  http: ^1.2.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  font_awesome_flutter: ^10.8.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend.ttf

flutter_native_splash:
  color: "#E8E8E8"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#E8E8E8"
    fullscreen: true
